### ISSUE TITLE
Webhook URL is always invalid.

### ISSUE THREAD

**Issue by lockness-Ko** [TracecatHQ/tracecat#119]
**Describe the bug**
The automatically generated webhook URL in the webhook action is always invalid. It looks to me as though the protocol (http://) , domain (somehost.local), and port (:8000) are not being put in the URL field.

**To Reproduce**
1. Login to tracecat.
2. Navigate to 'My first workflow' or Create a new workflow.
3. Drag a webhook Action out.
4. Set method to GET or POST.
5. Click save and observe the "Invalid Url" error.

**Expected behavior**
The webhook URL is valid and saves.

**Screenshots**
![image](https://github.com/TracecatHQ/tracecat/assets/42625905/1a88404a-288e-4270-85df-c8b3621d07e8)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 123.0.6312.124

**Additional context**
Stack trace:
```
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at _c (http://some_magic_host/_next/static/chunks/src_88564b._.js:5358:341)
    at http://some_magic_host/_next/static/chunks/node_modules__pnpm_9bbbde._.js:2876:23
    at http://some_magic_host/_next/static/chunks/node_modules__pnpm_9bbbde._.js:2850:23
    at http://some_magic_host/_next/static/chunks/src_88564b._.js:1114:359
    at div
    at http://some_magic_host/_next/static/chunks/src_88564b._.js:1066:353
    at Controller (http://some_magic_host/_next/static/chunks/5afbb_react-hook-form_dist_index_esm_mjs_5acd52._.js:516:39)
    at FormField (http://some_magic_host/_next/static/chunks/src_88564b._.js:1022:25)
    at ActionFormInputs (http://some_magic_host/_next/static/chunks/src_558fc8._.js:2948:29)
    at div
    at div
    at div
    at div
    at form
    at FormProvider (http://some_magic_host/_next/static/chunks/5afbb_react-hook-form_dist_index_esm_mjs_5acd52._.js:151:13)
    at div
    at ActionForm (http://some_magic_host/_next/static/chunks/src_558fc8._.js:3237:23)
    at div
    at WorkspacePanel (http://some_magic_host/_next/static/chunks/src_558fc8._.js:6190:190)
    at div
    at PanelWithForwardedRef (http://some_magic_host/_next/static/chunks/node_modules__pnpm_80b455._.js:121:34)
    at forwardRef(Panel)
    at div
    at PanelGroupWithForwardedRef (http://some_magic_host/_next/static/chunks/node_modules__pnpm_80b455._.js:1072:39)
    at forwardRef(PanelGroup)
    at ResizablePanelGroup (http://some_magic_host/_next/static/chunks/src_558fc8._.js:22:32)
    at Provider (http://some_magic_host/_next/static/chunks/node_modules__pnpm_9bbbde._.js:2750:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (http://some_magic_host/_next/static/chunks/node_modules__pnpm_cc8aab._.js:19869:29)
    at WorkflowBuilderProvider (http://some_magic_host/_next/static/chunks/src_88564b._.js:1671:36)
    at ReactFlowProvider (http://some_magic_host/_next/static/chunks/c81f2_@reactflow_core_dist_esm_index_mjs_c37535._.js:5083:30)
    at Workspace (http://some_magic_host/_next/static/chunks/src_558fc8._.js:6317:22)
    at InnerLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13425:11)
    at RedirectErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4472:9)
    at RedirectBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4480:11)
    at NotFoundBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4736:11)
    at Suspense
    at LoadingBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13517:11)
    at ErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4226:11)
    at InnerScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13336:9)
    at ScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13411:11)
    at RenderFromTemplateContext (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13641:44)
    at OuterLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13535:11)
    at InnerLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13425:11)
    at RedirectErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4472:9)
    at RedirectBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4480:11)
    at NotFoundBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4736:11)
    at Suspense
    at LoadingBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13517:11)
    at ErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4226:11)
    at InnerScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13336:9)
    at ScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13411:11)
    at RenderFromTemplateContext (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13641:44)
    at OuterLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13535:11)
    at div
    at EventFeedProvider (http://some_magic_host/_next/static/chunks/src_88564b._.js:4049:30)
    at WorkflowProvider (http://some_magic_host/_next/static/chunks/src_88564b._.js:680:29)
    at InnerLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13425:11)
    at RedirectErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4472:9)
    at RedirectBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4480:11)
    at NotFoundErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4728:9)
    at NotFoundBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4736:11)
    at LoadingBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13517:11)
    at ErrorBoundaryHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4180:9)
    at ErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4226:11)
    at InnerScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13336:9)
    at ScrollAndFocusHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13411:11)
    at RenderFromTemplateContext (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13641:44)
    at OuterLayoutRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_fe9c5a._.js:13535:11)
    at QueryClientProvider (http://some_magic_host/_next/static/chunks/node_modules__pnpm_9bbbde._.js:1920:30)
    at DefaultQueryClientProvider (http://some_magic_host/_next/static/chunks/src_d500b5._.js:19:39)
    at body
    at html
    at RedirectErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4472:9)
    at RedirectBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4480:11)
    at NotFoundErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4728:9)
    at NotFoundBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4736:11)
    at DevRootNotFoundBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4796:11)
    at ReactDevOverlay (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:11218:9)
    at HotReload (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:12005:11)
    at Router (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:12293:11)
    at ErrorBoundaryHandler (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4180:9)
    at ErrorBoundary (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:4226:11)
    at AppRouter (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:12642:13)
    at ServerRoot (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:12905:11)
    at RSCComponent
    at Root (http://some_magic_host/_next/static/chunks/80d23_next_dist_client_02473e._.js:12915:11)
```

**Comment by topher-lo** [comment]
Needs further clarification

**Comment by daryllimyt** [comment]
https://docs.tracecat.com/installation#expose-runner-via-ngrok

Closing as this is a feature due to configuration TRACECAT__RUNNER_URL. This env var sets the domain for the webhook.

Please see linked docs for further clarification.

**Comment by topher-lo** [comment]
Indeed, webhooks are registered in the runner service, so the URL host of the webhooks is the runner
